import { MiniKitContextProvider } from './providers/MiniKitProvider';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <MiniKitContextProvider>{children}</MiniKitContextProvider>
      </body>
    </html>
  );
}

export async function generateMetadata(): Promise<Record<string, any>> {
  const URL = import.meta.env.VITE_PUBLIC_URL as string;
  const projectName = import.meta.env.VITE_ONCHAINKIT_PROJECT_NAME as string;
  const heroImage = import.meta.env.VITE_APP_HERO_IMAGE as string;
  const splashImage = import.meta.env.VITE_APP_SPLASH_IMAGE as string;
  const splashBg = import.meta.env.VITE_SPLASH_BACKGROUND_COLOR as string;
  return {
    title: projectName,
    description: 'Generated by `create-onchain --mini`',
    other: {
      'fc:frame': JSON.stringify({
        version: 'next',
        imageUrl: heroImage,
        button: {
          title: `Launch ${projectName}`,
          action: {
            type: 'launch_frame',
            name: projectName,
            url: URL,
            splashImageUrl: splashImage,
            splashBackgroundColor: splashBg,
          },
        },
      }),
    },
  };
}